### ISSUE TITLE
Matching orders and riders

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/pickup#1]
After the stack group formation, we have orders-rider matching to do: including stacks and non stacked orders

**Comment by wonjoonSeol-WS** [comment]
Hello James, 

I appreicate your time for answering the question. It was very helpful thank you.

To briefly describe the matching problem - it is to allocate the most suitable rider for a given order. (Or skip allocation if there is no suitable rider OR there exist better set of orders for all available riders)

There are both hard and soft constraints to consider in real world - to name a few (1) food weight and volume (hard limit for rider bag capacity - not uniform sizes) for stacked orders (2) time window to deliver (3) different vehicle types (vehicle not homogenous - cycle, motorbike, car, walking etc..) (4) distance to restaurants and customer house (5) promotion / commission fee to pay to rider (6) special requirement: payment devices, etc..

For simplicity, the easiest approach for rider allocation would be to only consider distance and allocate the closest one to any given restaurant within a viable time frame.

**Comment by JamesBremner** [comment]
_For simplicity, the easiest approach for rider allocation would be to only consider distance and allocate the closest one to any given restaurant within a viable time frame._

 - We have a restaurant location for the current stack
 - We have a vector of rider locations
 - Insert rider locations into a quad tree
 - Find riders within acceptable distance of restaurant
 - Filter acceptable riders by other constraints
 - Select closest of acceptable riders.

The quad tree approach is significantly faster than a straight search through the vector of riders if you have more than 100 riders.  For detailed discussion of this, see https://github.com/JamesBremner/quadtree

**Comment by JamesBremner** [comment]
I have coded this feature using the quadtree to find riders acceptable close to the restaurant.

Here is the time profile

```
C:\Users\James\code\pickup\bin>pickup.exe
Pickup
Orders per hour                  20000
Order collection time mins     5
Restaurants                    5000
Pickup window mins             5
Maximum order preparation mins 15

1407 order stacks created

raven::set::cRunWatch code timing profile
Calls            Mean (secs)      Total           Scope
       1           2.80885            2.80885            stacking orders
    1407        6.64136e-06     0.0093444       Optimize stack delivery route
    1407        1.08955e-07     0.0001533       Allocate rider to stack
```

**Comment by JamesBremner** [comment]
Here is the rider allocation code

https://github.com/JamesBremner/pickup/blob/3e7b3e32e0fd0e78a42940bb9d27e70b981ad0f2/src/cStack.cpp#L66-L96

**Comment by JamesBremner** [comment]
This implementation of matching riders to orders handles 1400 order stacks in less than 1/5th of a millisecond.

Is this implementation correct?  The performance seems very satisfactory, but perhaps I have missed something?

**Comment by JamesBremner** [comment]
I have refactored the rider assignment to conform to OOD ( object orientated design ) principles

The code in not essentially changed - mainly the loop over the stacked order vector is moved out of the main function and into the assign method of the cRiderPool class.

https://github.com/JamesBremner/pickup/blob/03301adf136ee228d7cf0949a3f79f55fe7be3a3/src/cRider.cpp#L38-L71

**Comment by wonjoonSeol-WS** [comment]
The quad-tree approach seem like a great idea. 

For map we tend to use hexagonal grid rather than square grid to minimise the quantization error.
- The earth is spherical shape - map projection does introduce size error.
- Hexagon has the same distance to each points, square has different length diagnoally - it would tends to favour riders in diagonal distance in quad tree search.
https://eng.uber.com/h3/

Seems like there are already a few researches on quad tree using the hexagonal grid: https://www.researchgate.net/publication/338964786_Lattice_Quad-Tree_Indexing_Algorithm_for_a_Hexagonal_Discrete_Global_Grid_System

**Comment by JamesBremner** [comment]
The reason I used a rectangular grid is because you wrote

> If TSP computation on real road network is too slow to use for real-time on-demand service. I'd have to use manhattan distance instead (ditching road network altogether) and create simple network consisting of restaurant, delivery points as the nodes only. 

Changing the grid to hexagonal sounds like a major change.  If you want me to implement this change, you will need to open a new issue ( not just add it on to the end of an existing issue. ) and we can discuss it there.

Alternatively, I could change from the manhatten distance to Pythagorean.  ( The sphericity of the earth is not significant for the distances we are using )

**Comment by JamesBremner** [comment]
> square has different length diagnoally

Note that this is not true for Manhatten distance calculation.

**Comment by wonjoonSeol-WS** [comment]
Hello James, I believe you've done far more than what I've expected initially when I wrote the question. 
It was a lot of work - and I've gained huge insight seeing your work so thank you.

Here we actually use manhattan "haversine distance" (lon and lat), if we use haversine approximation performance-wise it does not differ too much from the "normal" manhattan.

**Comment by JamesBremner** [comment]
> Here we actually use manhattan "haversine distance"

Please move this discussion to issue #2

I think this issue can probably be closed.
